### ISSUE TITLE
Not really a issue more a request of feature. 

### ISSUE THREAD

**Issue by nerdtechse** [WeeJeWel/tv.plex#2]
When this app was published i made alot of flows that dimmed the lights where the tv that was used to play with plex. And it worked great both in my bedroom and in my tv room.  But after a while it wouldnt work anymore. I found out that becuase that i used appletv as player of plex. And some change was done to appletv os or client so now it doesnt share the name of the appletv anymore. And of that i cant get info of which player is used. 

So my question is would it be possible for this app to have a tag with ipadress of client as the player and server is local i can make flows that seperates the right player for my rooms. That would fix the problem for me. :)

And Emile im so greatful what you and your friends started with Homey.  As homey user since almost the begining i can say that a homey is like a gift that keeps giving. So many thanks for all the hard work!

**Comment by WeeJeWel** [comment]
I see that Apple did indeed change this since tvOS 16. Now it always returns 'Apple TV' regardless what you've named your Apple TV.

Unfortunately Plex didn't add an option to name your client in their app...

This is what the Plex API returns:

```
<Player address="172.18.0.5" device="Apple TV" machineIdentifier="F2E6DD28-3774-4B99-8C44-85EB7A5C48B8" model="6,2" platform="tvOS" platformVersion="18.1" product="Plex for Apple TV" profile="tvOS" state="playing" title="Apple TV" vendor="Apple" version="8.41" local="1" relayed="0" secure="0" userID="1"/>
```

It might be better to add the 'machineIdentifier' instead of the 'address' because it never changes. What do you think?

And thanks for the compliment! It's really nice to get positive feedback between all the complaints haha! :-)​

**Comment by nerdtechse** [comment]
Could it be possible to make 2 tags? One for machineIdentifier and one for player adress.  I use static ips for alot of things in my network so the ip change related to dhcp isnt a problem for me.  
But for the usual user maybe machineIdentifier is better but how will they know where to find it in a easy way? 

Nowadays some people often forget to say thank you when things are working. But they never forget to tell you when something isnt workning.. Its time to change that!

**Comment by WeeJeWel** [comment]
I've added the `Player ID` tag which is the client's UUID to Plex v1.3.3: https://homey.app/a/tv.plex/test/.

I don't like the 'Address' tag because it can change, and won't make sense when streaming from 5G for example. Note that you cal always fork the app :)

**Comment by nerdtechse** [comment]
That will work! 

Could you also add the tag to when player is stopped and paused? :) 

Thanks again for taking the time to fix this!

**Comment by WeeJeWel** [comment]
Ah of course. Added in [Plex v1.3.4](https://homey.app/a/tv.plex/test/).
